### ISSUE TITLE
SCRIPT DEPRECATION WARNING

### ISSUE THREAD

**Issue by rnsi** [Splines/raspi-captive-portal#6]
During installation, I get the following message:

                           SCRIPT DEPRECATION WARNING                    

  
  This script, located at https://deb.nodesource.com/setup_X, used to
  install Node.js is deprecated now and will eventually be made inactive.

  Please visit the NodeSource distributions Github and follow the
  instructions to migrate your repo.
  https://github.com/nodesource/distributions

  The NodeSource Node.js Linux distributions GitHub repository contains
  information about which versions of Node.js and which Linux distributions
  are supported and how to install it.
  https://github.com/nodesource/distributions

                          SCRIPT DEPRECATION WARNING

It still works for now, but will likely break later.

**Comment by Splines** [comment]
Thanks for noting. Luckily, the team at `nodesource` decided to not deprecate these scripts due to popular demand. See [their update here](https://github.com/nodesource/distributions?tab=readme-ov-file#new-update-%EF%B8%8F):

> Installation Scripts: Back by popular demand, the installation scripts have returned and are better than ever. See the installation instructions below for details on how to use them.

Note that I've upgraded to Node.js 20 in the new [v1.0.1 release](https://github.com/Splines/raspi-captive-portal/releases/tag/v1.0.1) of this repo.
